### ISSUE TITLE
changing buttons don't work

### ISSUE THREAD

**Issue by pino7421** [borisbu/OctoRelay#21] opened 2021-04-17 10:21 UTC
Hi,

i tried to change the name of the buttons but it does not work, also r3 en r4 are deactivated but still visible in the nav bar

grtz

**Comment by pino7421** [comment] 2021-04-18 10:01
Hi, 

I've had some issues with my smart filament detector and removed several plugins, and yes suddenly the text appeared in the navbar, but after installing the plugin for the filament detector they where gone again, so it probably has a conflict with that plugin or more..

**Comment by RobinTail** [comment] 2023-08-03 17:28
duplicate of #58

**Closed by RobinTail** 2023-08-03 17:28 UTC
