### ISSUE TITLE
Not switching on at start of print job

### ISSUE THREAD

**Issue by FlyingPete** [borisbu/OctoRelay#39] opened 2021-10-26 01:49 UTC
Hi, I have a small Prusa i3Mk3S+ print farm, all running OctoPrint with relay controlled nights on each printer.
I have tested with the OctoRelay plugin but I cannot get the switch on at start of print job to function, the switch off at completion works fine.
I have also tested with the Enclosure plugin, and switch on at start of print job works with that plugin.

**Comment by mattdy** [comment] 2021-11-08 12:18
I'm also experiencing this after updating to OctoPrint 1.7.2

Auto-off after print completion still appears to work, but auto-on is no longer functioning.

**Comment by schneemaier** [comment] 2021-12-04 13:22
I have the same issue. I usually print through Cura, but now i have connect to octoprint an manualy turn on the printer.

**Comment by FalcoonM** [comment] 2022-02-24 17:44
Issue is still present I guess. Turning off after a print job works flawlessly, but relay does not engage at start. Might this be related to how upload is handled. New print just show on a list and are unable to start if printer is not connected. I have just a data cable - no 5V between Pi and board, don't kno if this would affect the issue.

**Comment by tonysprenk** [comment] 2022-06-22 19:49
I'm having the same issue

**Comment by hcooper** [comment] 2022-11-28 20:02
I just filed https://github.com/borisbu/OctoRelay/pull/55 which fixes this for me.

The cause for me was that octorelay is processing other unactive configs too. In my case I was using pin 18, however there was an unactive config for "relay 3" which also used pin 18 which had `inverted_output=True`. So my pin 18 would go on, and then get turned off again straight away by the other config.

Until the fix is committed, if you use pins that conflict with any of the defaults listed below you might want to go in a put fake pin numbers in these configs:
```
R1 4
R2 17
R3 18
R4 23
R5 24
R6 25
R7 8
R8 7
```

**Comment by ninthclowd** [comment] 2023-06-01 14:38
> Until the fix is committed, if you use pins that conflict with any of the defaults listed below you might want to go in a put fake pin numbers in these configs:
> 
> ```
> R1 4
> R2 17
> R3 18
> R4 23
> R5 24
> R6 25
> R7 8
> R8 7
> ```

thanks for the workaround until #55 is merged!

**Closed** 2023-07-19 19:30 UTC

**Comment by RobinTail** [comment] 2023-07-19 19:34
🚀  @FlyingPete , the issue should be fixed in v1.4.1.
Please check it out, and in case it's not, please create another issue.
